repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        exclude: 'setup.cfg'
      - id: end-of-file-fixer
        exclude: 'setup.cfg'
      - id: debug-statements

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.0
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.0.7
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [
        'flake8-blind-except',
        'flake8-bandit',
        'flake8-comprehensions',
        'flake8-mutable',
        'flake8-bugbear',
        'flake8-broken-line',
        'flake8-print',
        'flake8-logging-format',
        'flake8-pytest-style',
        ]
